using UnityEngine;
using DG.DemiEditor;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;
using System.Collections.Generic;
using Utilities.Extensions;
using UnityEditor.UIElements;
using System;

public class IconThumbnailEditor : EditorWindow
{
    [SerializeField] VisualTreeAsset m_VisualTreeAsset = default;

    [SerializeField] GameObject selectedObject;
    [SerializeField] Texture2D previewTexture;

    // preview
    private const int _previewSize = 512;
    private Camera _previewCamera;
    private Scene _previewScene;
    private GameObject _previewInstance;
    private Light _previewLight, _fillLight;

    private Bounds _currentBounds;
    private float _baseDistance;
    private Vector3 _viewDirection = new Vector3(1, 0.5f, 1).normalized;

    private Label _label;
    private ListView _listView;
    private Vector3Field _cameraPositionField, _cameraRotationField;
    private ColorField _backgroundColorField;
    private Slider _distanceSlider, _objectRotationSlider;
    private Button _saveButton;

    private List<GameObject> _models = new();

    [MenuItem("Tools/Utilities/Icon Editor")]
    public static void ShowExample() => GetWindow<IconThumbnailEditor>();

    public void CreateGUI()
    {
        VisualElement root = rootVisualElement;
        VisualElement labelFromUXML = m_VisualTreeAsset.Instantiate();
        root.Add(labelFromUXML);

        _label = root.Q<Label>("Label");
        _listView = root.Q<ListView>("List");
        _cameraPositionField = root.Q<Vector3Field>("CameraPosition");
        _cameraRotationField = root.Q<Vector3Field>("CameraRotation");
        _backgroundColorField = root.Q<ColorField>("BackgroundColor");

        _distanceSlider = root.Q<Slider>("CameraDistance");
        _distanceSlider.lowValue = 0.2f;
        _distanceSlider.highValue = 5.0f;

        _objectRotationSlider = root.Q<Slider>("ObjectRotation");
        _objectRotationSlider.lowValue = 0f;
        _objectRotationSlider.highValue = 360f;

        _saveButton = root.Q<Button>("SaveButton");
        _saveButton.clicked += Export;

        _cameraPositionField.RegisterValueChangedCallback(OnCameraPositionChanged);
        _cameraRotationField.RegisterValueChangedCallback(OnCameraRotationChanged);
        _backgroundColorField.RegisterValueChangedCallback(OnCameraBackgroundColorChanged);
        _distanceSlider.RegisterValueChangedCallback(OnCameraDistanceChanged);
        _objectRotationSlider.RegisterValueChangedCallback(OnObjectRotationChanged);

        OnSelectionChange();
        Selection.selectionChanged += OnSelectionChange;
        _listView.selectionChanged += OnSelectItem;

        root.Q<VisualElement>("Content").dataSource = this;
    }

    private void Export()
    {
        _previewCamera.depthTextureMode = DepthTextureMode.Depth;
        UpdateCamera();

        // Use the actual texture generated by the camera
        SaveTextureAsPNG(previewTexture, selectedObject.name);
    }

    private void SaveTextureAsPNG(Texture2D texture, string fileName)
    {
        if (!texture) return;

        string path = EditorUtility.SaveFilePanel("Save Icon As PNG", Application.dataPath, $"{fileName}.png", "png");
        if (string.IsNullOrEmpty(path)) return;

        Texture2D exportTex = new Texture2D(_previewSize, _previewSize, TextureFormat.RGBA32, false);
        RenderTexture.active = _previewCamera.targetTexture;
        exportTex.ReadPixels(new Rect(0, 0, _previewSize, _previewSize), 0, 0);
        exportTex.Apply();

        byte[] pngData = exportTex.EncodeToPNG();
        if (pngData != null)
        {
            System.IO.File.WriteAllBytes(path, pngData);

            // Convert absolute path to relative "Assets/..." path
            string relativePath = FileUtil.GetProjectRelativePath(path);

            // Refresh database to register the new file
            AssetDatabase.ImportAsset(relativePath);

            // Access the importer to set Sprite settings
            TextureImporter importer = AssetImporter.GetAtPath(relativePath) as TextureImporter;
            if (importer != null)
            {
                importer.textureType = TextureImporterType.Sprite;
                importer.spriteImportMode = SpriteImportMode.Single;
                importer.maxTextureSize = 512;

                // Optional: Ensure alpha is handled correctly for UI
                importer.alphaIsTransparency = true;
                importer.mipmapEnabled = false;

                importer.SaveAndReimport();
            }

            Debug.Log($"Icon saved and imported as Sprite at: {relativePath}");
        }

        DestroyImmediate(exportTex);
    }

    private void OnObjectRotationChanged(ChangeEvent<float> evt)
    {
        if (!_previewCamera || _previewInstance == null) return;

        // Set the absolute rotation on the Y axis
        _previewInstance.transform.rotation = Quaternion.Euler(0f, evt.newValue, 0f);
        UpdateCamera();
    }

    private void OnCameraPositionChanged(ChangeEvent<Vector3> evt)
    {
        if (_previewCamera) _previewCamera.transform.position = evt.newValue;
        UpdateCamera();
    }

    private void OnCameraRotationChanged(ChangeEvent<Vector3> evt)
    {
        if (_previewCamera) _previewCamera.transform.rotation = Quaternion.Euler(evt.newValue);
        UpdateCamera();
    }

    private void OnCameraBackgroundColorChanged(ChangeEvent<Color> evt)
    {
        if (_previewCamera) _previewCamera.backgroundColor = evt.newValue;
        UpdateCamera();
    }

    private void OnCameraDistanceChanged(ChangeEvent<float> evt)
    {
        if (!_previewCamera || _previewInstance == null) return;

        float padding = evt.newValue;
        _previewCamera.transform.position = _currentBounds.center + (_baseDistance * padding * _viewDirection);
        _previewCamera.transform.LookAt(_currentBounds.center);

        _cameraPositionField.SetValueWithoutNotify(_previewCamera.transform.position);
        _cameraRotationField.SetValueWithoutNotify(_previewCamera.transform.rotation.eulerAngles);

        UpdateCamera();
    }

    private void UpdateCamera()
    {
        _previewCamera.Render();

        // Standardizing format to RGBA32 helps with editor-to-file visual consistency
        if (!previewTexture) previewTexture = new Texture2D(_previewSize, _previewSize, TextureFormat.RGBA32, false);

        RenderTexture.active = _previewCamera.targetTexture;
        previewTexture.ReadPixels(new Rect(0, 0, _previewSize, _previewSize), 0, 0);
        previewTexture.Apply();
        RenderTexture.active = null;
    }

    private void OnSelectItem(object item)
    {
        selectedObject = _models[_listView.selectedIndex];
        if (!selectedObject) return;

        _label.text = selectedObject.name;

        if (!_previewScene.IsValid()) _previewScene = EditorSceneManager.NewPreviewScene();

        if (!_previewCamera)
        {
            GameObject cameraGO = new("Preview Camera");
            SceneManager.MoveGameObjectToScene(cameraGO, _previewScene);

            _previewCamera = cameraGO.AddComponent<Camera>();
            _previewCamera.aspect = 1f;
            _previewCamera.clearFlags = CameraClearFlags.SolidColor;
            // Using standard ARGB32 for the render texture to match display expectations
            _previewCamera.targetTexture = new RenderTexture(_previewSize, _previewSize, 32, RenderTextureFormat.ARGB32);
            _previewCamera.scene = _previewScene;
        }

        SetupLights();

        if (_previewInstance) DestroyImmediate(_previewInstance);

        _previewInstance = new GameObject("Preview Instance");
        var model = Instantiate(selectedObject, _previewInstance.transform, false);
        _currentBounds = TransformExtensions.CalculateLocalBounds(model.transform);
        model.transform.localPosition = -_currentBounds.center;
        SceneManager.MoveGameObjectToScene(_previewInstance, _previewScene);

        if (_previewCamera && _previewInstance)
        {
            // Calculate framing
            _baseDistance = _currentBounds.extents.magnitude / Mathf.Sin(_previewCamera.fieldOfView * 0.5f * Mathf.Deg2Rad);

            // Default padding 1.1f gives a nice little border around the model
            _distanceSlider.SetValueWithoutNotify(1.1f);

            float padding = _distanceSlider.value;
            _previewCamera.transform.position = _currentBounds.center + (_baseDistance * padding * _viewDirection);
            _previewCamera.transform.LookAt(_currentBounds.center);

            _cameraPositionField.value = _previewCamera.transform.position;
            _cameraRotationField.value = _previewCamera.transform.rotation.eulerAngles;
        }

        UpdateCamera();
    }

    private void SetupLights()
    {
        if (!_previewLight)
        {
            GameObject lightGO = new("Preview Main Light");
            SceneManager.MoveGameObjectToScene(lightGO, _previewScene);
            _previewLight = lightGO.AddComponent<Light>();
            _previewLight.type = LightType.Directional;
            _previewLight.intensity = 1.5f;
            _previewLight.transform.rotation = Quaternion.Euler(50, -30, 0);
        }

        if (!_fillLight)
        {
            GameObject fillGO = new("Preview Fill Light");
            SceneManager.MoveGameObjectToScene(fillGO, _previewScene);
            _fillLight = fillGO.AddComponent<Light>();
            _fillLight.type = LightType.Directional;
            _fillLight.intensity = 0.7f; // Increased slightly for better PNG brightness
            _fillLight.transform.rotation = Quaternion.Euler(-10, 45, 0);
        }
    }

    private void OnSelectionChange()
    {
        _models = new List<GameObject>(Selection.gameObjects);

        _listView.itemsSource = _models;
        _listView.Rebuild();
        _listView.SetSelection(0);
    }

    private void OnDisable()
    {
        if (_previewCamera)
        {
            if (_previewCamera.targetTexture)
            {
                _previewCamera.targetTexture.Release();
                DestroyImmediate(_previewCamera.targetTexture);
            }
            DestroyImmediate(_previewCamera.gameObject);
        }

        if (_previewLight) DestroyImmediate(_previewLight.gameObject);
        if (_fillLight) DestroyImmediate(_fillLight.gameObject);
        if (_previewInstance) DestroyImmediate(_previewInstance);
        if (_previewScene.IsValid()) EditorSceneManager.ClosePreviewScene(_previewScene);
    }
}